apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-bluegreen
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        tier: frontend
        track: bluegreenREPLACED_BY_VERSION_DURING_BUILD
    spec:
      containers:
        - name: helloworld
          image: "10.0.0.13:18444/datarace/helloworld:THIS_STRING_IS_REPLACED_DURING_BUILD"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
      imagePullSecrets:
        - name: myregistrykey18444
