apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-bluegreen
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        tier: frontend
        track: bluegreen
    spec:
      containers:
        - name: helloworld
          image: "datarace/helloworld"
          ports:
            - name: http
              containerPort: 8000
      imagePullSecrets:
        - name: myregistrykey18444
